function U = readin( file )
  
%   p = @(t) [ cos(2*pi*t/6) ; sin(2*pi*t/6) ];
%   P = struct( ...
%     'e', p(0), ...
%     'ne', p(1), ...
%     'nw', p(2), ...
%     'w', p(3), ...
%     'sw', p(4), ...
%     'se', p(5) );

  P = struct( ...
    'e', [ 2 ; 0 ], ...
    'ne', [ 1 ; 1 ], ...
    'nw', [ -1 ; 1 ], ...
    'w', [ -2 ; 0 ], ...
    'sw', [ -1 ; -1 ], ...
    'se', [ 1 ; -1 ] );

  U = zeros( 0, 2 );
  
  fid = fopen( file );
  
  l = fgetl( fid );
  while ischar( l )
    
    T = regexp( l, '(se|sw|nw|ne|e|w)', 'tokens' );
    
    U( end+1, : ) = sum( cell2mat( cellfun( @(t) P.(t{1}), T, 'UniformOutput', false ) ), 2 )'; %#ok<AGROW>
    
    l = fgetl( fid );
    
  end
  
  fclose( fid );
  
end