
% T = readin( 'demo1.in' );
T = readin( 'data.in' );

P = puzzle( T );

disp( uint64( prod( [ P(1,1).id P(1,end).id P(end,1).id P(end,end).id ] ) ) );

%%

sym = @(M) M(end:-1:1,:); rot = @(M)sym(M');

NESSY = [ ...
  '                  # ' ; ...
  '#    ##    ##    ###' ; ...
  ' #  #  #  #  #  #   ' ] == '#';

spot = @(M) conv2( conv2( M, NESSY, 'same' ) == sum( NESSY(:) ), [ zeros(3,1) rot(rot(NESSY)) ], 'same' ) == 1;

I = cell2mat( arrayfun( @(p)p.tile(2:end-1,2:end-1), P, 'UniformOutput', false ) );

S = spot(I) | ...
  rot(rot(rot(spot(rot(I))))) | ...
  rot(rot(spot(rot(rot(I))))) | ...
  rot(spot(rot(rot(rot(I))))) | ...
  spot(sym(I)) | ...
  rot(rot(rot(spot(rot(sym(I)))))) | ...
  rot(rot(spot(rot(rot(sym(I)))))) | ...
  rot(spot(rot(rot(rot(sym(I)))))) ;

disp( sum( I(:) & ~S(:) ) );
