
% P = readin( 'demo1.in' );
% P = readin( 'demo2.in' );
% P = readin( 'demo3.in' );
P = readin( 'data.in' );

ok1 = [ ...
  ~cellfun( @isempty, { P.byr } ); ...
  ~cellfun( @isempty, { P.iyr } ); ...
  ~cellfun( @isempty, { P.eyr } ); ...
  ~cellfun( @isempty, { P.hgt } ); ...
  ~cellfun( @isempty, { P.hcl } ); ...
  ~cellfun( @isempty, { P.ecl } ); ...
  ~cellfun( @isempty, { P.pid } ) ];

disp( sum( all( ok1, 1 ) ) );

%%

ok2 = check( P );
disp( sum( all( ok2, 1 ) ) );
